### ISSUE TITLE
关于语料预处理的问题

### ISSUE THREAD

**Issue by ningshixian** [lingluodlut/Att-ChemdNER#1]
你好，我想问下Chemical的原始语料用Genia tagger分词后，对应的BIO标签该如何获取？因为分词后的语料与标签文件给定的实体位置不一致，而且部分单词也被切分了，难以跟原本的标签对上，请问你是如何处理的？谢谢

**Comment by lingluodlut** [comment]
@ningshixian 
你好，我是在原始语料上先对实体做上标记（在实体前后加入特定标签），然后再分词，再根据标记获取BIO标签。

**Comment by ningshixian** [comment]
我明白了，请问可以共享这部分代码吗？

**Comment by ningshixian** [comment]
好的，谢谢

**Comment by bluesea0** [comment]
> @ningshixian
> 你好，我是在原始语料上先对实体做上标记（在实体前后加入特定标签），然后再分词，再根据标记获取BIO标签。

你好，请问您使用的 **特定标签** 是什么呢？可以使用“#”吗？

**Comment by lingluodlut** [comment]
@huanting74 
你好，取一个语料中没有出现过的字符串即可，例如“AAAAA”之类的。

**Comment by bluesea0** [comment]
@lingluodlut 好的感谢
