### ISSUE TITLE
assertion error on training Bi-LSTM CRF

### ISSUE THREAD

**Issue by nitya-yekkirala** [lingluodlut/Att-ChemdNER#3]
Conversion of the second argument of issubdtype from `float` to `np.floating` is deprecated. In future, it will be treated as `np.float64 == np.dtype(float).type`.
  from ._conv import register_converters as _register_converters
Using TensorFlow backend.
Using TensorFlow backend.
Traceback (most recent call last):
  File "train.py", line 176, in <module>
    assert os.path.isfile(opts.train)
AssertionError

**Comment by lingluodlut** [comment]
Please check the path of inputfile. And we run our code using theano backend.

**Comment by nitya-yekkirala** [comment]
My bad didn't shift the backend to theano. After correcting the path and shifting the backend to theano, the issue got resolved. Thanks a bunch and great work on entity extraction.
