### ISSUE TITLE
ImportError: No module named tensorflow_backend

### ISSUE THREAD

**Issue by SeekPoint** [lingluodlut/Att-ChemdNER#5]
Successfully installed theano-0.9.0
You are using pip version 9.0.3, however version 10.0.1 is available.
You should consider upgrading via the 'pip install --upgrade pip' command.
mldl@mldlUB1604:~/ub16_prj/Att-ChemdNER/src$ python train.py --train trainfile --dev devfile --test testfile --pre_emb word_embedding.model 
Using TensorFlow backend.
Traceback (most recent call last):
  File "train.py", line 12, in <module>
    from utils import create_input
  File "/home/mldl/ub16_prj/Att-ChemdNER/src/utils.py", line 187, in <module>
    import initializations;
  File "/home/mldl/ub16_prj/Att-ChemdNER/src/initializations.py", line 3, in <module>
    import  backend as K
  File "/home/mldl/ub16_prj/Att-ChemdNER/src/backend/__init__.py", line 67, in <module>
    from .tensorflow_backend import *
ImportError: No module named tensorflow_backend
mldl@mldlUB1604:~/ub16_prj/Att-ChemdNER/src$

**Comment by bluesea0** [comment]
Have you solved the problem yet?

**Comment by lingluodlut** [comment]
@huanting74 You may run our code using Tenforflow backend from the error message. But our code is based on Theano 0.9.0 and python 2.7. You should switch to Theano backend.

**Comment by bluesea0** [comment]
Thank you so much. I run it successfully.
