### ISSUE TITLE
关于AttenTrain.py的代码

### ISSUE THREAD

**Issue by qizaijie** [lingluodlut/Att-ChemdNER#6]
def step(self,state,attended,source):
        #from theano.gradient import disconnected_grad;
        #state=disconnected_grad(state_);
        #M_state=T.dot(self.W_A_h,state) ;

        _energy=self.scoreFun(attended,state,self.W_A)
        energy=T.nnet.softmax(_energy);
        #energy=self.softmaxReScale(_energy,0.02);
        #energy=self.reScale(energy.flatten(),0.02).reshape((1,-1))
        #energyIndex=energy.flatten().argmin(axis=-1);
        glimpsed=(energy.T*source).sum(axis=0)
        #glimpsed=source[energyIndex];
        return energy.flatten(),glimpsed;

    def link(self,attended,state,source):
        step_function=self.step;
        attended_=T.tanh(T.dot(attended,self.W_A_X))+self.b_A_X;
        #attended_=attended;
        [energy,glimpsed],_=theano.scan(fn=step_function,
                            sequences=[attended_],
                               outputs_info=None,
                            non_sequences=[attended_,source]);
        self.energy=energy;
        
        #combine 
        #combine=T.concatenate([glimpsed,attended],axis=-1);
        combine=T.concatenate([glimpsed,source],axis=-1);
        combined=T.tanh(T.dot(combine,self.W_A_combine))+self.b_A_combine;
        #no source
        #combined=T.tanh(T.dot(glimpsed,self.W_A_combine))+self.b_A_combine;
        return combined;
在model.py中，调用了此link函数，传入的参数是（final_output,final_c,final_output），此link函数中有个scan函数，传入到step_funtion中的是attended_，attended_，source，传入了两个一样的attended_，那么_energy=self.scoreFun(attended,state,self.W_A)得到的不是零吗？传入的attended和state相等的话计算距离公式不是为零吗。小菜鸟提个问，希望能得到解释，万分感谢！

**Comment by bluesea0** [comment]
你好，我也有同样的问题，scoreFun计算出的距离为0？
是否`AttentionLayer`类中的`link`方法中：
```
class AttentionLayer(Layer):
    ...
    def link(self,attended,state,source):
        ....
        [energy,glimpsed],_=theano.scan(fn=step_function,
                            sequences=[attended_],
                               outputs_info=None,
                            non_sequences=[attended_,source]);
        ....
    ....
```
`sequences`参数应该传入 `state`，而非 `attended_ `呢？

**Comment by lingluodlut** [comment]
@huanting74 这里相当于现在的自注意力机制，是通过输入的词向量attendedInput计算相似度，由于这是词向量矩阵，所以用attendedInput和attendedInput计算可以得到每个词和其他词的相似度，你也可以自己输出计算结果。

**Comment by bluesea0** [comment]
感谢您的回复！
