### ISSUE TITLE
ImportError: No module named tensorflow_backend

### ISSUE THREAD

**Issue by dfatimazohra** [lingluodlut/Att-ChemdNER#7]
Hi there,

I am having issue running Att-ChemdNER.

I have installed the following package:

- Package                Version  
- ---------------------- ---------
- absl-py                0.2.2    
- astor                  0.7.1    
- backports.weakref      1.0.post1
- bleach                 1.5.0    
- enum34                 1.1.6    
- funcsigs               1.0.2    
- futures                3.2.0    
- gast                   0.2.0    
- grpcio                 1.13.0   
- h5py                   2.8.0    
- html5lib               0.9999999
- Keras                  2.2.0    
- Keras-Applications     1.0.2    
- Keras-Preprocessing    1.0.1    
- Markdown               2.6.11   
- mock                   2.0.0    
- numpy                  1.14.5   
- pbr                    4.1.0    
- pip                    10.0.1   
- protobuf               3.6.0    
- PyYAML                 3.13     
- scipy                  1.1.0    
- setuptools             39.1.0   
- six                    1.11.0   
- tensorboard            1.9.0    
- tensorflow-gpu         1.3.0    
- tensorflow-tensorboard 0.1.8    
- termcolor              1.1.0    
- Theano                 0.9.0    
- Werkzeug               0.14.1   
- wheel                  0.31.1 

After running the command line in the readme:

`python train.py --train trainfile --dev devfile --test testfile --pre_emb word_embedding.model
`

I am getting this error:

```
Using TensorFlow backend.
Traceback (most recent call last):
  File "train.py", line 12, in <module>
    from utils import create_input
  File "/home/fdaha/virt_env_att/Att-ChemdNER-master/src/utils.py", line 187, in <module>
    import initializations;
  File "/home/fdaha/virt_env_att/Att-ChemdNER-master/src/initializations.py", line 3, in <module>
    import  backend as K
  File "/home/fdaha/virt_env_att/Att-ChemdNER-master/src/backend/__init__.py", line 67, in <module>
    from .tensorflow_backend import *
ImportError: No module named tensorflow_backend
```

**Comment by lingluodlut** [comment]
You may run our code using Tenforflow backend from the error message. But our code is based on Theano 0.9.0 and python 2.7. You should switch to Theano backend.
