### ISSUE TITLE
参数“sentencesLevelLoss”的设定问题

### ISSUE THREAD

**Issue by bluesea0** [lingluodlut/Att-ChemdNER#8]
请问在您的模型性能达到最优时，sentencesLevelLoss的值的设置（True or False），以及计算句子水平的损失和doc水平的损失具体有什么区别呢？十分感谢。

**Comment by lingluodlut** [comment]
@huanting74 你好，最优模型是文档级模型，所以sentencesLevelLoss值为false，当为true时，使用的是句子级loss，文档级的loss是把句子级loss进行累加。

**Comment by bluesea0** [comment]
明白了，谢谢您的回复。
