### ISSUE TITLE
关于对新文档进行预测标注

### ISSUE THREAD

**Issue by wen-fei** [lingluodlut/Att-ChemdNER#9]
谢谢你的工作。
我想请问的是，你代码里对新文档预测标注的应该只有chemdner数据集的？
我跑了cdr数据集的模型，用来预测，报错越界，主要是loder.py文件的226行，
`
      ner=[dic_to_id[w[4]] for w in s];
`
这里报list越界，debug之后感觉和数据集有关。
不知道作者能否提供什么帮助，非常感谢

**Comment by wen-fei** [comment]
补充一句，我的目标是识别出疾病实体，能做到吗？感谢作者

**Comment by lingluodlut** [comment]
我们模型训练时只使用了化学药物实体，所以提供的模型只能识别化学药物不能识别疾病，你可以用疾病实体数据集重新训练一个模型来识别疾病实体。
